version: 2

project_name: arbok

before:
  hooks:
    - go mod tidy

builds:
  - id: server
    main: ./cmd/server
    binary: arbok
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    builds:
      - server
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - config.sample.toml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: mr-karan
    name: arbok
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"

dockers:
  - image_templates:
      - "ghcr.io/mr-karan/arbok:{{ .Version }}"
      - "ghcr.io/mr-karan/arbok:latest"
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - config.sample.toml
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=Secure HTTP tunnels using WireGuard
      - --label=org.opencontainers.image.url=https://github.com/mr-karan/arbok
      - --label=org.opencontainers.image.source=https://github.com/mr-karan/arbok
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
