# Production Configuration Example
# This shows how to configure Arbok for production with Cloudflare

[app]
verbose = false
# Domain for HTTP API and website (can be behind Cloudflare)
domain = "arbok.mrkaran.dev"

[auth]
# Add API keys for production security
api_keys = [
    "your-secret-api-key-here",
]

[tunnel]
default_ttl = "24h"
cleanup_interval = "5m"

[server]
cidr = "10.100.0.0/24"
listen_port = 54321
# Generate a new private key for production!
# wg genkey
private_key = "YOUR_PRODUCTION_PRIVATE_KEY_HERE"

# WireGuard endpoint - MUST be direct connection (not behind Cloudflare)
# Options:
# 1. Direct server IP: "45.32.xxx.xxx:54321"
# 2. DNS-only subdomain: "wg.arbok.mrkaran.dev:54321" (set to grey cloud in Cloudflare)
endpoint = "45.32.xxx.xxx:54321"

[http]
listen_addr = ":8080"
allowed_origins = ["https://arbok.mrkaran.dev"]