services:
  arbok:
    image: ghcr.io/mr-karan/arbok:latest
    container_name: arbok
    environment:
      TZ: Asia/Kolkata
    volumes:
      - ./config.toml:/app/config.toml  # Mount your local config.toml file
    ports:
      - "8080:8080"
      - "54321:54321/udp"  # WireGuard port
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    devices:
      - /dev/net/tun:/dev/net/tun
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:8080/health -O - || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    command: ["./arbok", "--config", "/app/config.toml"]
    networks:
      - arbok

networks:
  arbok:
    name: arbok
