services:
  arbok:
    image: ghcr.io/mr-karan/arbok:latest
    container_name: arbok
    environment:
      TZ: Asia/Kolkata
      # Override config via environment variables
      ARBOK_SERVER_APP__DOMAIN: "tunnel.yourdomain.com"
      ARBOK_SERVER_AUTH__API_KEYS: '["admin-mrkaran-prod-VB7PGkPB9jmzZCXXzC"]'
      ARBOK_SERVER_SERVER__PRIVATE_KEY: "uLu0FutcktFMZ1rTMKvE/LRkGBAeoBJcMvoX4a+Sxmw="
      ARBOK_SERVER_SERVER__CIDR: "10.100.0.0/24"
      ARBOK_SERVER_SERVER__LISTEN_PORT: "54321"
      ARBOK_SERVER_HTTP__LISTEN_ADDR: ":8080"
    ports:
      - "100.64.13.114:17770:8080"
      - "100.64.13.114:54321:54321/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    devices:
      - /dev/net/tun:/dev/net/tun
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:8080/health -O - || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped