services:
  arbok:
    image: ghcr.io/mr-karan/arbok:latest
    container_name: arbok
    environment:
      TZ: Asia/Kolkata
    configs:
      - source: arbok_config
        target: /app/config.toml
    ports:
      - "100.64.13.114:17770:8080"
      - "100.64.13.114:54321:54321/udp"  # WireGuard port
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    devices:
      - /dev/net/tun:/dev/net/tun
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:8080/health -O - || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    command: ["./arbok", "--config", "/app/config.toml"]

configs:
  arbok_config:
    content: |
      [app]
      verbose = false
      domain = "tunnel.yourdomain.com"  # CHANGE THIS

      [auth]
      api_keys = []  # Add API keys like ["key1", "key2"] if needed

      [tunnel]
      default_ttl = "24h"
      cleanup_interval = "5m"

      [server]
      cidr = "10.100.0.0/24"
      listen_port = 54321
      private_key = "YOUR_WIREGUARD_PRIVATE_KEY"  # CHANGE THIS - generate with: wg genkey

      [http]
      listen_addr = ":8080"
      allowed_origins = ["*"]
